server:
  port: 8087
  servlet:
    context-path: /mqtt

spring:
  mqtt:
    url: tcp://192.168.3.10:1883 # ?????????
    username: user
    password: 666666
    client:
      id: ${random.value}
    default: # MQTT ?????????????????????
      topic: topic # ?????????
    completionTimeout: 3000 # ????
