server:
  port: 8087
  servlet:
    context-path: /mqtt

spring:
  mqtt:
    url: tcp://192.168.3.10:1883
    username: user
    password: 123456
#    client:
#      id: ${random.value} # 要同时启动 Provider 和 Consumer，就要给 Provider 和 Consumer 设置不同的 client-id
    providerClientId: pan_provider
    consumerClientId: pan_consumer
    default:
      topic: topic1
    completionTimeout: 3000
